Update ZAP.yml

diff --git a/.github/workflows/ZAP.yml b/.github/workflows/ZAP.yml
--- a/.github/workflows/ZAP.yml
+++ b/.github/workflows/ZAP.yml
@@ -19,9 +19,9 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y wget
-        wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
-        tar -xvzf ZAP_2.14.0_Linux.tar.gz
-        sudo mv ZAP_2.14.0 /opt/zaproxy
+        wget https://github.com/zaproxy/zaproxy/releases/download/v2.15.0/ZAP_2.15.0_Linux.tar.gz
+        tar -xvzf ZAP_2.15.0_Linux.tar.gz
+        sudo mv ZAP_2.15.0 /opt/zaproxy
         sudo ln -s /opt/zaproxy/zap.sh /usr/local/bin/zap
 
     - name: Start ZAP in the background
@@ -38,4 +38,4 @@ jobs:
 
     - name: Stop ZAP
       run: |
-  
+        zap-cli shutdown || echo "Failed to stop ZAP"
